language: swift
osx_image: xcode9
xcode_project: HamsterUIKit.xcodeproj
xcode_scheme: HamsterUIKit
env:
  global:
    - FRAMEWORK_NAME=<HamsterUIKit>
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  # - carthage bootstrap
before_deploy:
  - carthage build --no-skip-current
